ECHO-1529: Added changelog version-0.13
echoprotocol/echowiki pull request #71
Opened 2019-11-06 10:38 UTC by Ashes17b

2019-11-06 11:14 UTC, viktor32 commented on changelogs/0.13.md
> +## Changed data structures
Probably we should create files with these structures and leave here only a link to files

2019-11-11 14:33 UTC, kstdl commented on api-reference/echo-objects/objects-order.md
> +|account_object_type|2|
id should be id_type(e.g.: 1.2.x for accounts)

2019-11-11 14:33 UTC, kstdl commented on api-reference/echo-objects/dynamic-global-property-object.md
> +        static const uint8_t space_id = implementation_ids;
remove unneeded data from structs

2019-11-11 15:40 UTC, kstdl requested changes

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +    - Operation `sidechain_btc_approve_aggregate_operation`
there should be link to op

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +## Added
describe for what are needed all added or add links to another page with full description

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +	- Field `committee_member_ids_in_script` in `btc_address_object`, `btc_intermediate_deposit_object`, `btc_aggregating_object` is `map<account_id_type, echo::sidechain::btc::public_key>` now
looks like mess

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +    - Method `get_account_deposits` return type `variants` now
what could be in variants? maybe links should be added

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +- Issue block_reward_operation for every account
Block reward are accumulated and issues with block_reward_operation during maintenance

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +- Calling `echorand::on_transaction`
remove

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +- `Registrer_account` example in wallet-API
remove. changed comment of method for doxygen

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +- Contract results getters
Contract results getters are optimized

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +- Added limit for x86 contract size in the `create_contract_operation`
mentioned in `added` section. remove

2019-11-11 15:40 UTC, kstdl commented on changelogs/0.13.md
> +- Echorand, async dispatching message to active agreement
Echorand messages are dispatched asyncly

2019-11-12 10:44 UTC, merged